"""
proxy/cli.py

The Warden command line.

    warden init                      write a starter policy + workspace
    warden inspect TOOL [ARGS-JSON]  evaluate one hypothetical call, explained
    warden run -- CMD [ARGS...]      run a real MCP server behind Warden
    warden verify                    independently verify the audit chain

Every command that needs a policy fails closed: no policy file and no
--policy flag means the built-in deny-everything default, never a permissive
guess. `warden init` is how you opt INTO capability, explicitly.
"""

import argparse
import asyncio
import json
import sys
from pathlib import Path

from proxy.policy.engine import PolicyEngine, PolicyValidationError
from proxy.audit.log import AuditLog
from proxy.core.request import Request
from proxy.core.mission import Mission
from proxy.runtime.mediator import Mediator
from proxy.transport.mcp import MCPProxy

DEFAULT_POLICY_FILE = "warden.policy.yaml"

# The secure default: a syntactically valid policy that permits NOTHING.
# Used when no policy file exists — Warden without configuration is a wall.
_DENY_ALL_POLICY = """\
version: 1
mode: enforce
workspace_root: '{workspace}'
tools: {{}}
redaction:
  enabled: true
  block_secrets_in_args: true
inbound_inspection:
  enabled: true
  on_injection_detected: escalate
audit:
  enabled: true
  path: '{audit}'
"""

_STARTER_POLICY = """\
# Warden policy — generated by `warden init`. Deny by default: only what is
# written here is permitted. See config/policy.yaml in the repo for the full
# annotated reference.
version: 1
mode: enforce            # switch to `monitor` to log decisions without enforcing
workspace_root: '{workspace}'

execution:
  timeout_seconds: 30    # watchdog: a tool call that outlives this is abandoned

egress:
  enabled: true
  allowed_hosts: []      # empty = all network destinations denied

tools:
  read_file:
    tier: auto
    inspect_response: true
    path_args: [path]
  list_directory:
    tier: auto
    inspect_response: true
    path_args: [path]
  write_file:
    tier: escalate       # a human approves every write
    inspect_args: true
    path_args: [path]
  delete_file:
    tier: escalate
    path_args: [path]

redaction:
  enabled: true
  detectors: [api_keys, aws_keys, private_keys, emails, ssn, credit_cards]
  block_secrets_in_args: true

inbound_inspection:
  enabled: true
  on_injection_detected: escalate   # annotate | escalate | deny

audit:
  enabled: true
  path: '{audit}'
"""


def _load_engine(policy_arg: str | None, tmp_dir: Path | None = None) -> PolicyEngine:
    if policy_arg:
        return PolicyEngine(policy_arg)
    default = Path(DEFAULT_POLICY_FILE)
    if default.exists():
        return PolicyEngine(str(default))
    # No policy anywhere: run on the built-in deny-all default (fail closed).
    workdir = tmp_dir or Path.cwd()
    fallback = workdir / ".warden.default.policy.yaml"
    fallback.write_text(_DENY_ALL_POLICY.format(
        workspace=(workdir / "workspace").as_posix(),
        audit=(workdir / "audit" / "warden_audit.db").as_posix()))
    print("[warden] no policy found — running on the built-in DENY-ALL default. "
          "Run `warden init` to create a real policy.", file=sys.stderr)
    return PolicyEngine(str(fallback))


def _audit_path(engine: PolicyEngine) -> str:
    return (engine.policy.get("audit", {}) or {}).get("path", "audit/warden_audit.db")


def cmd_init(args) -> int:
    target = Path(args.policy or DEFAULT_POLICY_FILE)
    if target.exists() and not args.force:
        print(f"[warden] {target} already exists (use --force to overwrite)", file=sys.stderr)
        return 1
    workspace = Path(args.workspace or "workspace").resolve()
    workspace.mkdir(parents=True, exist_ok=True)
    audit = Path("audit/warden_audit.db")
    target.write_text(_STARTER_POLICY.format(workspace=workspace.as_posix(), audit=audit.as_posix()))
    print(f"[warden] wrote {target}")
    print(f"[warden] workspace: {workspace}")
    print("[warden] next: `warden inspect read_file '{\"path\": \"notes.txt\"}'`")
    return 0


def cmd_inspect(args) -> int:
    try:
        engine = _load_engine(args.policy)
    except (PolicyValidationError, FileNotFoundError) as e:
        print(f"[warden] policy error: {e}", file=sys.stderr)
        return 2
    tool_args = {}
    if args.args:
        try:
            tool_args = json.loads(args.args)
        except json.JSONDecodeError as e:
            print(f"[warden] ARGS must be JSON: {e}", file=sys.stderr)
            return 2
    mission = None
    if args.mission_tools:
        mission = Mission(args.mission or "(cli mission)",
                          set(t.strip() for t in args.mission_tools.split(",") if t.strip()))
    decision = engine.decide(Request.normalize(args.tool, tool_args), mission)
    print(decision.explain())
    return 0 if decision.verdict.value == "ALLOW" else 1


def cmd_verify(args) -> int:
    try:
        engine = _load_engine(args.policy)
    except (PolicyValidationError, FileNotFoundError) as e:
        print(f"[warden] policy error: {e}", file=sys.stderr)
        return 2
    path = args.audit or _audit_path(engine)
    if not Path(path).exists():
        print(f"[warden] no audit log at {path}", file=sys.stderr)
        return 2
    log = AuditLog(path)
    report = log.verify_chain_detail()
    log.close()
    if report["intact"]:
        print(f"[warden] audit chain INTACT — {report['entries']} entr"
              f"{'y' if report['entries'] == 1 else 'ies'} verified ({path})")
        return 0
    print(f"[warden] audit chain BROKEN at seq={report['broken_at_seq']}: "
          f"{report['problem']} ({report['entries']} entries verified before the break)")
    return 1


def cmd_run(args) -> int:
    if not args.server_cmd:
        print("[warden] usage: warden run -- <mcp-server-command> [args...]", file=sys.stderr)
        return 2
    try:
        engine = _load_engine(args.policy)
    except (PolicyValidationError, FileNotFoundError) as e:
        print(f"[warden] policy error: {e}", file=sys.stderr)
        return 2
    audit = AuditLog(args.audit or _audit_path(engine))
    mission = None
    if args.mission_tools:
        mission = Mission(args.mission or "(cli mission)",
                          set(t.strip() for t in args.mission_tools.split(",") if t.strip()))
    mediator = Mediator(engine, audit)
    proxy = MCPProxy(mediator, args.server_cmd, mission=mission)
    print(f"[warden] mediating MCP server: {' '.join(args.server_cmd)} "
          f"(mode: {mediator.mode})", file=sys.stderr)
    try:
        return asyncio.run(proxy.run())
    finally:
        audit.close()


def cmd_stats(args) -> int:
    """v1.5.4: operational telemetry derived from the forensic audit log."""
    from proxy.audit.telemetry import snapshot, render
    if args.audit:
        path = args.audit  # explicit path: no policy needed at all
    else:
        try:
            engine = _load_engine(args.policy)
            path = _audit_path(engine)
        except (PolicyValidationError, FileNotFoundError) as e:
            print(f"[warden] policy error: {e}", file=sys.stderr)
            return 2
    if not Path(path).exists():
        print(f"[warden] no audit log at {path}", file=sys.stderr)
        return 2
    report = snapshot(path)
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print(render(report, top=args.top))
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="warden",
                                description="Zero-trust security runtime for AI agents")
    p.add_argument("--policy", help=f"policy file (default: ./{DEFAULT_POLICY_FILE}, "
                                    "else built-in deny-all)")
    sub = p.add_subparsers(dest="command", required=True)

    sp = sub.add_parser("init", help="write a starter policy and workspace")
    sp.add_argument("--workspace", help="workspace directory (default: ./workspace)")
    sp.add_argument("--force", action="store_true")
    sp.set_defaults(func=cmd_init)

    sp = sub.add_parser("inspect", help="evaluate one hypothetical tool call")
    sp.add_argument("tool")
    sp.add_argument("args", nargs="?", help="tool arguments as JSON")
    sp.add_argument("--mission", help="mission statement")
    sp.add_argument("--mission-tools", help="comma-separated allowed tools")
    sp.set_defaults(func=cmd_inspect)

    sp = sub.add_parser("verify", help="verify the audit chain end to end")
    sp.add_argument("--audit", help="audit db path (default: from policy)")
    sp.set_defaults(func=cmd_verify)

    sp = sub.add_parser("stats", help="operational telemetry from the audit log")
    sp.add_argument("--audit", help="audit db path (default: from policy)")
    sp.add_argument("--json", action="store_true", help="machine-readable output")
    sp.add_argument("--top", type=int, default=10,
                    help="rows shown per listing (default 10)")
    sp.set_defaults(func=cmd_stats)

    sp = sub.add_parser("run", help="run an MCP server behind Warden")
    sp.add_argument("--audit", help="audit db path (default: from policy)")
    sp.add_argument("--mission", help="mission statement")
    sp.add_argument("--mission-tools", help="comma-separated allowed tools")
    sp.add_argument("server_cmd", nargs=argparse.REMAINDER,
                    help="-- followed by the real MCP server command")
    sp.set_defaults(func=cmd_run)
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if getattr(args, "server_cmd", None) and args.server_cmd and args.server_cmd[0] == "--":
        args.server_cmd = args.server_cmd[1:]
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
